#ifndef __NVMDATA_H__
#define __NVMDATA_H__

#include "nvmapi.h"


/* define unique nvram data ID */
enum {
	NVM_DATA_ID(SCAN_DPI_200_ADC_A),
	NVM_DATA_ID(SCAN_DPI_200_ADC_B),
	NVM_DATA_ID(SCAN_DPI_300_ADC_A),
	NVM_DATA_ID(SCAN_DPI_300_ADC_B),
	NVM_DATA_ID(SCAN_DPI_600_ADC_A),
	NVM_DATA_ID(SCAN_DPI_600_ADC_B),
	NVM_DATA_ID(SCAN_DPI_1200_ADC_A),
	NVM_DATA_ID(SCAN_DPI_1200_ADC_B),

	NVM_DATA_ID(SCAN_DPI_200_CIS_A),
	NVM_DATA_ID(SCAN_DPI_200_CIS_B),
	NVM_DATA_ID(SCAN_DPI_300_CIS_A),
	NVM_DATA_ID(SCAN_DPI_300_CIS_B),
	NVM_DATA_ID(SCAN_DPI_600_CIS_A),
	NVM_DATA_ID(SCAN_DPI_600_CIS_B),
	NVM_DATA_ID(SCAN_DPI_1200_CIS_A),
	NVM_DATA_ID(SCAN_DPI_1200_CIS_B),

	NVM_DATA_ID(SCAN_DPI_200_CALIBDATA),
	NVM_DATA_ID(SCAN_DPI_300_CALIBDATA),
	NVM_DATA_ID(SCAN_DPI_600_CALIBDATA),
	NVM_DATA_ID(SCAN_DPI_1200_CALIBDATA),
};


#endif /* __NVMDATA_H__ */
